"""Freddie Mac Release 47 (July 2026) column order and explicit types."""
import pyarrow as pa

ORIG = '''classic_fico first_payment_date first_time_homebuyer_indicator maturity_date msa mortgage_insurance_percentage number_of_units occupancy_status original_cltv original_dti original_upb original_ltv original_interest_rate channel prepayment_penalty_indicator amortization_type property_state property_type postal_code loan_identifier loan_purpose original_loan_term number_of_borrowers seller_name super_conforming_flag pre_harp_loan_sequence_number special_eligibility_program harp_indicator property_valuation_method interest_only_indicator vantage_score_4_0'''.split()
PERF = '''loan_identifier monthly_reporting_period current_actual_upb current_loan_delinquency_status loan_age remaining_months_to_legal_maturity defect_settlement_date modification_flag zero_balance_code zero_balance_effective_date current_interest_rate current_non_interest_bearing_upb due_date_of_last_paid_installment mi_recoveries net_sales_proceeds non_mi_recoveries total_expenses legal_costs maintenance_and_preservation_costs taxes_and_insurance miscellaneous_expenses actual_loss cumulative_modification_costs interest_rate_step_indicator payment_deferral_flag estimated_ltv zero_balance_removal_upb delinquent_accrued_interest delinquency_due_to_disaster borrower_assistance_plan current_period_modification_costs current_interest_bearing_upb mortgage_insurance_cancellation_indicator servicer_name bankruptcy_cramdown_costs'''.split()
INTEGERS = set('''classic_fico mortgage_insurance_percentage number_of_units original_cltv original_dti original_ltv original_loan_term number_of_borrowers vantage_score_4_0 loan_age remaining_months_to_legal_maturity estimated_ltv'''.split())
MONEY = set('''original_upb current_actual_upb current_non_interest_bearing_upb mi_recoveries net_sales_proceeds non_mi_recoveries total_expenses legal_costs maintenance_and_preservation_costs taxes_and_insurance miscellaneous_expenses actual_loss cumulative_modification_costs zero_balance_removal_upb delinquent_accrued_interest current_period_modification_costs current_interest_bearing_upb bankruptcy_cramdown_costs'''.split())
RATES = {'original_interest_rate','current_interest_rate'}
SCHEMAS = {kind: pa.schema([(n, pa.int32() if n in INTEGERS else pa.decimal128(18,2) if n in MONEY else pa.decimal128(7,3) if n in RATES else pa.string()) for n in names]) for kind,names in [('origination',ORIG),('performance',PERF)]}
GUIDE = 'https://www.freddiemac.com/fmac-resources/research/pdf/general_user_guide_july_2026.pdf'

